import { ILazyCanvas, Export, IFonts } from "../types";
import { Canvas, SKRSContext2D, SvgExportFlag } from "@napi-rs/canvas";
import { LayersManager } from "./managers/LayersManager";
import { RenderManager } from "./managers/RenderManager";
import { FontsManager } from "./managers/FontsManager";

export class LazyCanvas implements ILazyCanvas {
    width: number | 0;
    height: number | 0;
    canvas: Canvas;
    ctx: SKRSContext2D;
    layers: LayersManager;
    render: RenderManager;
    fonts: FontsManager;
    exportType: Export;

    constructor() {
        this.width = 0;
        this.height = 0;
        this.canvas = new Canvas(0, 0);
        this.ctx = this.canvas.getContext('2d');
        this.layers = new LayersManager();
        this.render = new RenderManager(this);
        this.fonts = new FontsManager();
        this.exportType = Export.Buffer;
    }

    /**
     * Set the export type
     * @param type {Export} - The `export` type
     */
    public setExportType(type: Export) {
        this.exportType = type;
        switch (type) {
            case Export.Buffer:
                this.canvas = new Canvas(this.width, this.height);
                this.ctx = this.canvas.getContext('2d');
                break;
            case Export.CTX:
                break;
            case Export.SVG:
                this.canvas = new Canvas(this.width, this.height, SvgExportFlag.RelativePathEncoding);
                this.ctx = this.canvas.getContext('2d');
                break;
        }
        return this;
    }

    /**
     * Replace base fonts with custom fonts by special file.
     * Use this method before loading fonts by `FontManager`.
     * The file should be generated by the following instructions:
     * @see https://github.com/NMMTY/LazyCanvas/blob/main/scripts/FontsGenerate.md
     * @param fonts {IFonts[]} - The `fonts` to set
     */
    setFonts(fonts: IFonts) {
        this.fonts = new FontsManager(fonts);
        return this;
    }

    /**
     * Set the SVG export flag. This method should be called after `setExportType` method.
     * @param flag {SvgExportFlag} - The `flag` of the SVG export
     */
    setSvgExportFlag(flag: SvgExportFlag) {
        if (this.exportType === Export.SVG) {
            this.canvas = new Canvas(this.width, this.height, flag);
            this.ctx = this.canvas.getContext('2d');
        }
        return this
    }

    /**
     * Create a new canvas. This method should be called before any other methods.
     * @param width {number} - The `width` of the canvas
     * @param height {number} - The `height` of the canvas
     */
    create(width: number, height: number) {
        this.width = width;
        this.height = height;
        this.canvas = new Canvas(width, height);
        this.ctx = this.canvas.getContext('2d');
        this.layers = new LayersManager();
        this.render = new RenderManager(this);
        return this;
    }
}
